global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'citizen-command-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['citizen-command-service:8080']
        labels:
          application: 'Citizen Command Application'
  - job_name: 'citizen-query-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['citizen-query-service:8080']
        labels:
          application: 'Citizen Query Service Application'
rule_files:
  - 'alerts.rules.yml'