# kubernetes-manifests/citizen-query-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizen-query-service
  labels:
    app: citizen-query-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citizen-query-service
  template:
    metadata:
      labels:
        app: citizen-query-service
    spec:
      containers:
        - name: citizen-query-service
          image: tomasgimenez/citizen-query-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-profile-docker
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: citizen-query-service
  labels:
    app: citizen-query-service
spec:
  selector:
    app: citizen-query-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer