# kubernetes-manifests/redis-deployment-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-quarantine
  labels:
    app: redis-quarantine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-quarantine
  template:
    metadata:
      labels:
        app: redis-quarantine
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          command: ["redis-server", "--appendonly", "yes"]
---
apiVersion: v1
kind: Service
metadata:
  name: redis-quarantine
  labels:
    app: redis-quarantine
spec:
  selector:
    app: redis-quarantine
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP